### ISSUE TITLE
Tests all code cells

### ISSUE THREAD

**Issue by djvita** [bollwyvl/nosebook#9]
Hey, I know you placed it in the README, but I'm seeing that this "tests" code cells that are not Unit Tests.

The [ipython_nose](https://github.com/taavi/ipython_nose) is implemented as:  
>Add `%nose` to your notebook and run that cell. That will discover your `test_*` functions, run them, and report how many passed and how many failed, with stack traces for each failure.

So It would be nice for this to skip cells that don't have `def test`, and ignore empty cells. A workaround I thougtht of was  to add `unittest.skip()` on the non-test cells, but that ignored cell execution even.

Using I'm on 3.0.0-f75fda4 and is running on: Python 2.7.6  and your latest nosebook version. 

Maybe related: errors on the test cases don't have to do with the Unit test:

**Comment by djvita** [comment]
ERORR:
Traceback (most recent call last):
    /home/notebook/djvita/local/lib/python2.7/site-packages/nosebook.py line 151 in runTest
      msg = self.iopub.get_msg(block=True, timeout=1)
    /usr/local/lib/python2.7/dist-packages/IPython/kernel/blocking/channels.py line 57 in get_msg
      raise Empty
   Empty:

**Comment by bollwyvl** [comment]
> So It would be nice for this to skip cells that don't have def test

Yeah, tried to make it pretty clear in the README: its primary use case is testing if notebooks consistently create the same output, such that "normal" embedded code output becomes the "test". This is more of an integration testing/validation approach than unit testing. Shamefully, I don't actually _use_ it that way on the project itself, really, but test plugins are funny to test.

_So anyhow..._ I am __not__ going to change the default behaviour, but you are welcome to check out #10 where I've added something that might float your boat: `nosebook-match-cell` will let you specifically opt-in your test cells... but it won't even run the other cells, so there may be some odd challenges... i.e. your `import` cells will need to have tests defined in them, etc. I suppose a second option, say `nosebook-match-cell-setup` which allowed cells to be run, but their output ignored, would avoid that particular problem. Let me know if that is a showstopper, and I'll add it to that PR before cutting the next version, otherwise I'll release that.

> Maybe related: errors on the test cases don't have to do with the Unit test: 

Are you talking about your test cases, or `nosebook`'s test cases?

If your tests, can you help me by providing the cell/case in question?

If `nosebook`'s tests, how exactly did you run them? As you can see in by [cheat sheet](http://nbviewer.ipython.org/github/bollwyvl/nosebook/blob/master/Automation.ipynb) and `.travis.yml`, I am testing using `python setup.py test`, and it works a charm. plain old `nosetests` doesn't do the imports correctly or something.

It could also be a 2.7 thing: I do want to test against 2.7, but hadn't yet, as I would need to craft a second set of notebooks that would have the appropriate kernel outputs, then only pick them based on travis groups. Or something. Issue raised (#11).

**Comment by djvita** [comment]
I resolved the error through my test cases. I'll experiment with the  `nosebook-match-cell`. Thanks for the quick response!

**Comment by bollwyvl** [comment]
As an update, I started working on the tox infrastructure to test against py2/3 and ipython2/3/dev... once that, and travis, are good to go, I'll definitely be cutting a new release, as the requirements.txt will change.

Thanks for the interest! I look forward to hearing if #10 meets your needs!
